DROP TABLE IF EXISTS client;
DROP TABLE IF EXISTS adm;
DROP TABLE IF EXISTS wallet;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

